preload = /home/xeyossr/Resimler/Wallpaper/penguens.jpg
#preload = /home/xeyossr/Resimler/Wallpaper/alena-aenami-horizon-1k.jpg
wallpaper = eDP-1,/home/xeyossr/Resimler/Wallpaper/penguens.jpg
#wallpaper = HDMI-A-1,/home/yusuf/Pictures/Screenshots/wallpapers/alena-aenami-horizon-1k.jpg
